### ISSUE TITLE
what is this 'rh' about?

### ISSUE THREAD

**Issue by hayguen** [johnsonjh/rh#3]
Could not find any description what this program does.
Neither README nor usage() or any other file does explain this!

**Comment by johnsonjh** [comment]
It's a mirror of http://sources.vsta.org:7100/rh - an old "find"-like tool

I should add some proper documentation

**Comment by johnsonjh** [comment]
Closed by https://github.com/johnsonjh/rh/commit/571c099357c34f138dd7f2155ffdf54ec370a80b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5 + https://github.com/johnsonjh/rh/commit/571c099357c34f138dd7f2155ffdf54ec370a80b#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
